learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs"""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
	# Головна сторінка
	path('', views.index, name='index'),
	# Сторінка, що відображає всі теми
	path('topics/', views.topics, name='topics'),
	# Сторінка, присвячена окремій темі
	path('topics/<int:topic_id>/', views.topic, name='topic'),
	# Сторінка для додавання нової теми
	path('new_topic/', views.new_topic, name='new_topic'),
	# Сторінка для додавання новго допису
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	# Сторінка для редагування допису
	path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Визначити регулярні вирази URL"""

from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
	# Додати уставні URL auth (автентифікації)
	path('', include('django.contrib.auth.urls')),
	# Сторінка реєстрації
	path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
	"""Тема, яку вивчає користувач"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		"""Повернути рядкове представлення моделі"""
		return self.text

class Entry(models.Model):
	"""Якась конкретна інформація до цієї теми"""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""Повертає представлення моделі у string"""
		if len(self.text) > 50:
			return f"{self.text[:50]}..."
		else:
			return self.text 

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
	"""Головна сторінка "Learning Log"."""
	return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
	"""Відобразити всі теми"""
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {'topics': topics}
	return render(request, 'learning_logs/topics.html', context)

def check_topic_owner(topic, request):
	"""Пересвідчитись, що тема належить поточному користувачеві"""
	if topic.owner != request.user:
		raise Http404

@login_required
def topic(request, topic_id):
	"""Показати одну тему та всі її дописи"""
	topic = get_object_or_404(Topic, id=topic_id)
	check_topic_owner(topic, request)
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
	"""Додати нову тему"""
	if request.method != 'POST':
		# Жодних даних не відправлено; створити порожню форму
		form = TopicForm()
	else:
		# Відправлений POST; обробити дані
		form = TopicForm(data=request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return redirect('learning_logs:topics')
	# Показати порожню або недійсну форму
	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
	"""Додати новий допис для конкретної теми"""
	topic = get_object_or_404(Topic, id=topic_id)
	check_topic_owner(topic, request)
	if request.method != 'POST':
		# Жодних даних не надіслано; створити порожню форму
		form = EntryForm()
	else:
		# Отримані дані у POST-запиті; обробити дані
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic 
			new_entry.save()
			return redirect('learning_logs:topic', topic_id=topic_id)
	# Показати порожню або недійсну форму
	context = {'topic': topic, 'form': form}
	return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
	"""Редагувати існуючий допис"""
	entry = get_object_or_404(Entry, id=entry_id)
	topic = entry.topic
	check_topic_owner(topic, request)
	if request.method != 'POST':
		# Початковий запит; попередньо заповнити форму поточним записом
		form = EntryForm(instance=entry)
	else:
		# Надіслані дані POST; обробити дані
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('learning_logs:topic', topic_id=topic.id)
	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
	"""Зареєстувати нового користувача"""
	if request.method != 'POST':
		# Порожню форму реєстрації
		form = UserCreationForm()
	else:
		# Опрацювати заповнену форму
		form = UserCreationForm(data=request.POST)
		if form.is_valid():
			new_user = form.save()
			# Авторизувати користувача та скерувати його на головну сторінку
			login(request, new_user)
			return redirect('learning_logs:index')
	# Показати порожню або недійсну форму
	context = {'form': form}
	return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Learning Log</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
      Learning Log</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:topics'%}">
              Теми</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text"}>Привіт, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Вийти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">
                Зареєструватися</a></li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Увійти</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
  <h2>Редагуйте допис.</h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form">
  	{% csrf_token %}
  	{% bootstrap_form form %}
    {% buttons %}
  	  <button name="submit" class="btn btn-primary">Зберегти зміни</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Відстежуйте своє навчання.</h1>

    <p class="lead">Створіть власний журнал спостережень та зберігайте список тем, 
        які ви вивчаєте. Щоразу, коли ви дізнаєтеся щось нове про тему, 
        робіть запис, підсумовуючи те, що ви дізналися.</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Зареєструватися &raquo;</a>
  </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
  <h2>Додайте новий допис.</h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
  	{% csrf_token %}
  	{% bootstrap_form form %}
    {% buttons %}
  	  <button name='submit' class="btn btn-primary">Додати допис</button>
    {% endbuttons %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h2>Додайте нову тему.</h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
  	{% csrf_token %}
  	{% bootstrap_form form %}
    {% buttons %}
  	  <button name="submit" class="btn btn-primary">Додати тему</button>
    {% endbuttons %}
  </form>

 {% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Додати новий допис</a>
  </p>
  
  	{% for entry in entries %}
  	  <div class="card mb-3">
        <h4 class="card-header">
  	  	  {{ entry.date_added|date:'M d, Y H:i' }}
          <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
              редагувати допис</a></small>
        </h4>
        <div class="card-body">
  	  	  {{ entry.text|linebreaks }}
        </div>
      </div>
  	{% empty %}
  	  <p>Для цієї теми ще немає дописів</p>
  	{% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Теми</h1>
{% endblock page_header %}

{% block content %}
  <ul>
  	{% for topic in topics %}
  	  <li><h3>
  	  	<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  	  </h3></li>
  	{% empty %}
  	  <li><h3>Ще не було додано жодної теми</h3></li>
  	{% endfor %}
  </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Додати нову тему</a></h3>
{% endblock content %}